version: "3"

services:
  dotnet:
    build: ./CopaFilmesAPI
    container_name: copa-api
    ports:
      - "5000:5000"
    networks:
      - net
  angular:
    build: ./CopaFilmesSPA
    container_name: copa-spa
    ports:
      - "4200:4200"
    networks:
      - net
networks:
  net: